export const news = {
  pagination: { count: 25, limit: 25, offset: 0, total: 10000 },
  data: [
    {
      author: null,
      category: 'general',
      country: 'us',
      description: 'Nikita Chibrin, a former soldier who was part of the unit accused of massacres in Bucha, says he is willing to testify against his former brothers in arms.',
      image: 'https://i.dailymail.co.uk/1s/2022/12/14/10/65570057-0-image-a-10_1671012566397.jpg',
      language: 'en',
      source: 'dailymail',
      published_at: '2022-12-14T10:29:19Z',
      title: 'Defector who fled Russian army describes horrors committed by his unit',
      url: 'https://www.dailymail.co.uk/news/article-11536691/Defector-fled-Russian-army-describes-horrors-committed-unit.html?ns_mchannel=rss&ito=1490&ns_campaign=1490'
    },
    {
      author: 'zee business',
      category: 'business',
      country: 'us',
      description: 'HDFC Bank FD Interest Rate: HDFC Bank has hiked FD (fixed deposit) interest rates on fixed deposits of less than Rs 2 crore. ',
      image: null,
      language: 'en',
      source: 'Zee Business',
      published_at: '2022-12-14T10:29:16Z',
      title: 'HDFC Bank FD interest rates hiked; senior citizens to get up to 7.75% return',
      url: 'https://www.zeebiz.com/personal-finance/news-hdfc-bank-fd-interest-rates-today-latest-2022-increase-senior-citizens-to-get-up-to-775-return-update-212880'
    },
    {
      author: 'Equities News Editor',
      category: 'general',
      country: 'us',
      description: 'Mark Cudmore and Anna Edwards break down today&#8217;s key themes for analysts and investors on &#8220;Bloomberg Markets Europe.&#8221; Follow Bloomberg for business news & analysis, up-to-the-minute market data, &#8230; Read Full Story at source (may require registration)The post Markets Live: Equities Price Action, Post-US CPI Print, Pre-Fed Decision appeared first on ForexTV.',
      image: null,
      language: 'en',
      source: 'forextv',
      published_at: '2022-12-14T10:29:14Z',
      title: 'Markets Live: Equities Price Action, Post-US CPI Print, Pre-Fed Decision',
      url: 'https://forextv.com/equities/markets-live-equities-price-action-post-us-cpi-print-pre-fed-decision/'
    },
    {
      author: 'Gold Editor',
      category: 'general',
      country: 'us',
      description: 'In the previous trade, the precious metal closed at Rs 54,595 per 10 grams. Silver also climbed Rs 682 to Rs 69,176 per kg. &#8221;The gold price was steady in the Asian trading session after prices surged to a more than five-month high in the previous session on the back of softer-than-expected US consumer inflation, [&#8230;]The post Gold gains Rs 318; silver climbs Rs 682 appeared first on ForexTV.',
      image: null,
      language: 'en',
      source: 'forextv',
      published_at: '2022-12-14T10:29:12Z',
      title: 'Gold gains Rs 318; silver climbs Rs 682',
      url: 'https://forextv.com/xauusd-gold-us-dollar/gold-gains-rs-318-silver-climbs-rs-682/'
    },
    {
      author: 'GBP Editor',
      category: 'general',
      country: 'us',
      description: 'Traders now look to the key FOMC policy decision for a fresh directional impetus. The GBP/USD pair edges higher for the fifth successive day on Wednesday and climbs back closer to the 1.2400 mark &#8230;The post GBP/USD Price Analysis: Bulls have the upper hand near five-month top, FOMC awaited appeared first on ForexTV.',
      image: null,
      language: 'en',
      source: 'forextv',
      published_at: '2022-12-14T10:29:08Z',
      title: 'GBP/USD Price Analysis: Bulls have the upper hand near five-month top, FOMC awaited',
      url: 'https://forextv.com/gbp-british-pound/gbp-usd-price-analysis-bulls-have-the-upper-hand-near-five-month-top-fomc-awaited/'
    },
    {
      author: 'GBP Editor',
      category: 'general',
      country: 'us',
      description: 'GBP/USD capitalized on the broad-based selling pressure surrounding the US Dollar and closed in positive territory for the fifth straight trading day on Tuesday. The pair seems to have lost its &#8230;The post GBP/USD Forecast: Pound Sterling needs to flip 1.2400 into support to extend rally appeared first on ForexTV.',
      image: null,
      language: 'en',
      source: 'forextv',
      published_at: '2022-12-14T10:29:07Z',
      title: 'GBP/USD Forecast: Pound Sterling needs to flip 1.2400 into support to extend rally',
      url: 'https://forextv.com/gbp-british-pound/gbp-usd-forecast-pound-sterling-needs-to-flip-1-2400-into-support-to-extend-rally/'
    },
    {
      author: 'Meteorologist Jason Dunning',
      category: 'general',
      country: 'us',
      description: "Today will be another quiet, sunny, and warm day. Watch out for some patches of fog this morning; otherwise, we'll enjoy mainly clear skies and highs in the low to mid 80s this afternoon. The post Forecast: Last quiet day before strong cold front arrives appeared first on NBC2 News.",
      image: null,
      language: 'en',
      source: 'nbc-2',
      published_at: '2022-12-14T10:28:48Z',
      title: 'Forecast: Last quiet day before strong cold front arrives',
      url: 'https://nbc-2.com/weather/forecast/2022/12/14/forecast-last-quiet-day-before-strong-cold-front-arrives/'
    },
    {
      author: 'ABMN Staff',
      category: 'general',
      country: 'us',
      description: 'WCG Wealth Advisors LLC Purchases Shares of 1,083 American Tower Co. (NYSE:AMT)',
      image: null,
      language: 'en',
      source: 'americanbankingnews',
      published_at: '2022-12-14T10:28:45Z',
      title: 'WCG Wealth Advisors LLC Purchases Shares of 1,083 American Tower Co. (NYSE:AMT)',
      url: 'https://www.americanbankingnews.com/2022/12/14/wcg-wealth-advisors-llc-purchases-shares-of-1083-american-tower-co-nyseamt.html'
    },
    {
      author: 'ABMN Staff',
      category: 'general',
      country: 'us',
      description: 'WCG Wealth Advisors LLC Takes $292,000 Position in Halliburton (NYSE:HAL)',
      image: null,
      language: 'en',
      source: 'americanbankingnews',
      published_at: '2022-12-14T10:28:45Z',
      title: 'WCG Wealth Advisors LLC Takes $292,000 Position in Halliburton (NYSE:HAL)',
      url: 'https://www.americanbankingnews.com/2022/12/14/wcg-wealth-advisors-llc-takes-292000-position-in-halliburton-nysehal.html'
    },
    {
      author: 'ABMN Staff',
      category: 'general',
      country: 'us',
      description: 'Short Interest in Argonaut Gold Inc. (OTCMKTS:ARNGF) Rises By 65.8%',
      image: null,
      language: 'en',
      source: 'americanbankingnews',
      published_at: '2022-12-14T10:28:41Z',
      title: 'Short Interest in Argonaut Gold Inc. (OTCMKTS:ARNGF) Rises By 65.8%',
      url: 'https://www.americanbankingnews.com/2022/12/14/short-interest-in-argonaut-gold-inc-otcmktsarngf-rises-by-65-8.html'
    },
    {
      author: 'ABMN Staff',
      category: 'general',
      country: 'us',
      description: 'Short Interest in AppYea, Inc. (OTCMKTS:APYP) Rises By 204.8%',
      image: null,
      language: 'en',
      source: 'americanbankingnews',
      published_at: '2022-12-14T10:28:41Z',
      title: 'Short Interest in AppYea, Inc. (OTCMKTS:APYP) Rises By 204.8%',
      url: 'https://www.americanbankingnews.com/2022/12/14/short-interest-in-appyea-inc-otcmktsapyp-rises-by-204-8.html'
    },
    {
      author: 'ABMN Staff',
      category: 'general',
      country: 'us',
      description: 'Short Interest in ANTA Sports Products Limited (OTCMKTS:ANPDY) Rises By 225.0%',
      image: null,
      language: 'en',
      source: 'americanbankingnews',
      published_at: '2022-12-14T10:28:41Z',
      title: 'Short Interest in ANTA Sports Products Limited (OTCMKTS:ANPDY) Rises By 225.0%',
      url: 'https://www.americanbankingnews.com/2022/12/14/short-interest-in-anta-sports-products-limited-otcmktsanpdy-rises-by-225-0.html'
    },
    {
      author: 'ABMN Staff',
      category: 'general',
      country: 'us',
      description: 'Short Interest in Arch Therapeutics, Inc. (OTCMKTS:ARTH) Rises By 579.3%',
      image: null,
      language: 'en',
      source: 'americanbankingnews',
      published_at: '2022-12-14T10:28:41Z',
      title: 'Short Interest in Arch Therapeutics, Inc. (OTCMKTS:ARTH) Rises By 579.3%',
      url: 'https://www.americanbankingnews.com/2022/12/14/short-interest-in-arch-therapeutics-inc-otcmktsarth-rises-by-579-3.html'
    },
    {
      author: 'ABMN Staff',
      category: 'general',
      country: 'us',
      description: 'Short Interest in ARC Group Worldwide, Inc. (OTCMKTS:ARCW) Rises By 269.2%',
      image: null,
      language: 'en',
      source: 'americanbankingnews',
      published_at: '2022-12-14T10:28:41Z',
      title: 'Short Interest in ARC Group Worldwide, Inc. (OTCMKTS:ARCW) Rises By 269.2%',
      url: 'https://www.americanbankingnews.com/2022/12/14/short-interest-in-arc-group-worldwide-inc-otcmktsarcw-rises-by-269-2.html'
    },
    {
      author: 'ABMN Staff',
      category: 'general',
      country: 'us',
      description: 'Short Interest in A.P. Møller &#8211; Mærsk A/S (OTCMKTS:AMKBY) Decreases By 62.6%',
      image: null,
      language: 'en',
      source: 'americanbankingnews',
      published_at: '2022-12-14T10:28:41Z',
      title: 'Short Interest in A.P. Møller &#8211; Mærsk A/S (OTCMKTS:AMKBY) Decreases By 62.6%',
      url: 'https://www.americanbankingnews.com/2022/12/14/short-interest-in-a-p-moller-maersk-a-s-otcmktsamkby-decreases-by-62-6.html'
    },
    {
      author: 'fm',
      category: 'general',
      country: 'us',
      description: 'Electricity Authority of Cyprus (EAC) trade unions suspended strike action scheduled for Wednesday that would have caused power cuts after Labour Labour Minister Kyriakos Kousios intervened. He arranged for unions to discuss grievances &#8220;within the next week&#8221; with energy and finance ministers. Unions said an extraordinary meeting was convened Tuesday at the initiative Kyriakos Kousios, whom they informed about the issues that concern EAC workers and fears about the future of the organisation and the energy sector. &#8220;During the consultation, it was agreed that the Minister of...',
      image: null,
      language: 'en',
      source: 'financialmirror',
      published_at: '2022-12-14T10:28:41Z',
      title: 'Threat of power cuts avoided',
      url: 'https://www.financialmirror.com/2022/12/14/threat-of-power-cuts-avoided/'
    },
    {
      author: 'ABMN Staff',
      category: 'general',
      country: 'us',
      description: 'Short Interest in AmeraMex International, Inc. (OTCMKTS:AMMX) Decreases By 91.2%',
      image: null,
      language: 'en',
      source: 'americanbankingnews',
      published_at: '2022-12-14T10:28:40Z',
      title: 'Short Interest in AmeraMex International, Inc. (OTCMKTS:AMMX) Decreases By 91.2%',
      url: 'https://www.americanbankingnews.com/2022/12/14/short-interest-in-ameramex-international-inc-otcmktsammx-decreases-by-91-2.html'
    },
    {
      author: 'ABMN Staff',
      category: 'general',
      country: 'us',
      description: 'Alpha Lithium Co. (OTCMKTS:APHLF) Short Interest Up 31.4% in November',
      image: null,
      language: 'en',
      source: 'americanbankingnews',
      published_at: '2022-12-14T10:28:40Z',
      title: 'Alpha Lithium Co. (OTCMKTS:APHLF) Short Interest Up 31.4% in November',
      url: 'https://www.americanbankingnews.com/2022/12/14/alpha-lithium-co-otcmktsaphlf-short-interest-up-31-4-in-november.html'
    },
    {
      author: 'ABMN Staff',
      category: 'general',
      country: 'us',
      description: 'Alps Alpine Co., Ltd. (OTCMKTS:APELY) Short Interest Up 291.7% in November',
      image: null,
      language: 'en',
      source: 'americanbankingnews',
      published_at: '2022-12-14T10:28:40Z',
      title: 'Alps Alpine Co., Ltd. (OTCMKTS:APELY) Short Interest Up 291.7% in November',
      url: 'https://www.americanbankingnews.com/2022/12/14/alps-alpine-co-ltd-otcmktsapely-short-interest-up-291-7-in-november.html'
    },
    {
      author: 'ABMN Staff',
      category: 'general',
      country: 'us',
      description: 'Australia and New Zealand Banking Group Limited (OTCMKTS:ANZBY) Short Interest Down 99.6% in November',
      image: null,
      language: 'en',
      source: 'americanbankingnews',
      published_at: '2022-12-14T10:28:40Z',
      title: 'Australia and New Zealand Banking Group Limited (OTCMKTS:ANZBY) Short Interest Down 99.6% in November',
      url: 'https://www.americanbankingnews.com/2022/12/14/australia-and-new-zealand-banking-group-limited-otcmktsanzby-short-interest-down-99-6-in-november.html'
    },
    {
      author: null,
      category: 'general',
      country: 'us',
      description: '(marketscreener.com) PRESS RELEASE &#61591; PARIS, 14 DECEMBER 2022 Tikehau Capital appoints Laurent-David Charbit as co-head of its private equity regenerative agriculture practice The appointment follows the creation of a global private equity impact strategy dedicated to...https://www.marketscreener.com/quote/stock/TIKEHAU-CAPITAL-34204863/news/Tikehau-Capital-appoints-Laurent-David-Charbit-as-co-head-of-its-private-equity-regenerative-agric-42543292/?utm_medium=RSS&utm_content=20221214',
      image: null,
      language: 'en',
      source: '4-traders',
      published_at: '2022-12-14T10:28:35Z',
      title: 'Tikehau Capital : appoints Laurent-David Charbit as co-head of its private equity regenerative agriculture practice',
      url: 'https://www.marketscreener.com/quote/stock/TIKEHAU-CAPITAL-34204863/news/Tikehau-Capital-appoints-Laurent-David-Charbit-as-co-head-of-its-private-equity-regenerative-agric-42543292/?utm_medium=RSS&utm_content=20221214'
    },
    {
      author: null,
      category: 'general',
      country: 'us',
      description: '(marketscreener.com) Paris, December 14th, 2022 Success of the restructuring process of Villages Nature Tourisme End of the accelerated safeguard procedure opened on July 29, 2022 for the benefit of the Company 1. Successful operations for Villages Nature Tourisme ...https://www.marketscreener.com/quote/stock/PIERRE-VACANCES-4783/news/Pierre-Vacances-Inside-Information-Other-news-releases-42543288/?utm_medium=RSS&utm_content=20221214',
      image: null,
      language: 'en',
      source: '4-traders',
      published_at: '2022-12-14T10:28:35Z',
      title: 'Pierre & Vacances : Inside Information / Other news releases',
      url: 'https://www.marketscreener.com/quote/stock/PIERRE-VACANCES-4783/news/Pierre-Vacances-Inside-Information-Other-news-releases-42543288/?utm_medium=RSS&utm_content=20221214'
    },
    {
      author: null,
      category: 'general',
      country: 'us',
      description: '(marketscreener.com) HomeNewsroomSiemens Gamesa and Capital Energy sign new contract for a 52-MW wind power plant in Spain Siemens Gamesa and Capital Energy sign new contract for a 52-MW wind power plant in Spain The company will supply 10 SG 5.0-145 wind turbines for a wind power...https://www.marketscreener.com/quote/stock/SIEMENS-GAMESA-RENEWABLE-140594/news/Siemens-Gamesa-Renewable-Energy-S-A-and-Capital-Energy-sign-new-contract-for-a-52-MW-wind-power-pl-42543286/?utm_medium=RSS&utm_content=20221214',
      image: null,
      language: 'en',
      source: '4-traders',
      published_at: '2022-12-14T10:28:34Z',
      title: 'Siemens Gamesa Renewable Energy S A : and Capital Energy sign new contract for a 52-MW wind power plant in Spain',
      url: 'https://www.marketscreener.com/quote/stock/SIEMENS-GAMESA-RENEWABLE-140594/news/Siemens-Gamesa-Renewable-Energy-S-A-and-Capital-Energy-sign-new-contract-for-a-52-MW-wind-power-pl-42543286/?utm_medium=RSS&utm_content=20221214'
    },
    {
      author: null,
      category: 'general',
      country: 'us',
      description: "(marketscreener.com) Robust in unsettled times Analysts' Conference 2022 Financial Year Frankfurt, 14 December 2022 We inspire with energy. Robustly on course for #climatepositive with a...https://www.marketscreener.com/quote/stock/MVV-ENERGIE-AG-496746/news/MVV-Energie-Analysts-Presentation-2022-FY-42543283/?utm_medium=RSS&utm_content=20221214",
      image: null,
      language: 'en',
      source: '4-traders',
      published_at: '2022-12-14T10:28:34Z',
      title: "MVV Energie : Analysts' Presentation 2022 FY",
      url: 'https://www.marketscreener.com/quote/stock/MVV-ENERGIE-AG-496746/news/MVV-Energie-Analysts-Presentation-2022-FY-42543283/?utm_medium=RSS&utm_content=20221214'
    },
    {
      author: null,
      category: 'general',
      country: 'us',
      description: '(marketscreener.com) Kifissia, 14 December 2022 AUTOHELLAS S.A. announces, in accordance to the provisions of law 3556/2007, that on the 12th of December 2022 President of the Board of Directors of AUTOHELLAS S.A. and General Manager Emmanouella Vassilakis , purchased 7.500 shares of Autohellas S.A. at a total value of Euro...https://www.marketscreener.com/quote/stock/AUTOHELLAS-S-A-6258920/news/Autohellas-S-A-Announcement-in-accordance-with-codified-law-3556-2007-42543284/?utm_medium=RSS&utm_content=20221214',
      image: null,
      language: 'en',
      source: '4-traders',
      published_at: '2022-12-14T10:28:34Z',
      title: 'Autohellas S A : Announcement in accordance with codified law 3556/2007',
      url: 'https://www.marketscreener.com/quote/stock/AUTOHELLAS-S-A-6258920/news/Autohellas-S-A-Announcement-in-accordance-with-codified-law-3556-2007-42543284/?utm_medium=RSS&utm_content=20221214'
    }
  ]
}
